const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];

window.addEventListener('scroll',()=>{const h=document.documentElement;const p=h.scrollTop/(h.scrollHeight-h.clientHeight)*100;$('#progressBar').style.width=`${p}%`});

const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.35});
$$('.reveal,.reveal-card').forEach(el=>revealObserver.observe(el));

const countObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting||e.target.dataset.done)return;e.target.dataset.done='1';const end=Number(e.target.dataset.count);const start=performance.now();const dur=1300;function tick(now){const t=Math.min(1,(now-start)/dur);e.target.textContent=Math.floor(end*(1-Math.pow(1-t,3))).toLocaleString('ko-KR');if(t<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}),{threshold:.6});
$$('[data-count]').forEach(el=>countObserver.observe(el));

function linePath(points){return points.map((p,i)=>`${i?'L':'M'} ${p[0]} ${p[1]}`).join(' ')}
function svgEl(name,attrs={}){const n=document.createElementNS('http://www.w3.org/2000/svg',name);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n}

function drawNational(){const svg=$('#nationalChart');const data=[['2021',4153],['2022',4235],['2023',5155],['2024',5432],['2025',5107]];const W=900,H=480,m={l:75,r:45,t:45,b:70};const max=6000;[0,2000,4000,6000].forEach(v=>{const y=m.t+(H-m.t-m.b)*(1-v/max);svg.append(svgEl('line',{x1:m.l,y1:y,x2:W-m.r,y2:y,class:'chart-grid'}));const t=svgEl('text',{x:m.l-14,y:y+6,'text-anchor':'end',class:'chart-label'});t.textContent=v.toLocaleString();svg.append(t)});const pts=data.map((d,i)=>[m.l+i*(W-m.l-m.r)/(data.length-1),m.t+(H-m.t-m.b)*(1-d[1]/max)]);svg.append(svgEl('path',{d:linePath(pts),class:'national-line'}));pts.forEach((p,i)=>{svg.append(svgEl('circle',{cx:p[0],cy:p[1],r:9,class:'chart-dot'}));const v=svgEl('text',{x:p[0],y:p[1]-20,'text-anchor':'middle',class:'chart-value',fill:'#ff7a2f'});v.textContent=data[i][1].toLocaleString();svg.append(v);const l=svgEl('text',{x:p[0],y:H-28,'text-anchor':'middle',class:'chart-label'});l.textContent=data[i][0];svg.append(l)});const x2024=pts[3][0]-((pts[3][0]-pts[2][0])*.5);svg.append(svgEl('line',{x1:x2024,y1:m.t,x2:x2024,y2:H-m.b,class:'law-marker'}));const lab=svgEl('text',{x:x2024+8,y:m.t+18,class:'law-marker-label'});lab.textContent='2024.7 법 시행';svg.append(lab)}

drawNational();

const regionData={daejeon:{name:'대전',color:'#4ab4f8',values:[70,107,114,96,80]},chungnam:{name:'충남',color:'#ffbe3b',values:[201,256,253,243,121]},chungbuk:{name:'충북',color:'#ff7a2f',values:[98,145,135,117,53]}};
function drawRegion(active='all'){const svg=$('#regionChart');svg.innerHTML='';const years=['2022','2023','2024','2025','2026.06'];const W=900,H=500,m={l:70,r:45,t:40,b:75},max=300;[0,100,200,300].forEach(v=>{const y=m.t+(H-m.t-m.b)*(1-v/max);svg.append(svgEl('line',{x1:m.l,y1:y,x2:W-m.r,y2:y,class:'chart-grid'}));const t=svgEl('text',{x:m.l-12,y:y+6,'text-anchor':'end',class:'chart-label'});t.textContent=v;svg.append(t)});years.forEach((y,i)=>{const x=m.l+i*(W-m.l-m.r)/(years.length-1);const t=svgEl('text',{x,y:H-30,'text-anchor':'middle',class:'chart-label'});t.textContent=y;svg.append(t)});Object.entries(regionData).forEach(([key,r])=>{const pts=r.values.map((v,i)=>[m.l+i*(W-m.l-m.r)/(years.length-1),m.t+(H-m.t-m.b)*(1-v/max)]);const path=svgEl('path',{d:linePath(pts),class:`region-line ${active!=='all'&&active!==key?'region-muted':''}`,stroke:r.color});svg.append(path);pts.forEach((p,i)=>{svg.append(svgEl('circle',{cx:p[0],cy:p[1],r:8,class:`region-dot ${active!=='all'&&active!==key?'region-muted':''}`,stroke:r.color}));const txt=svgEl('text',{x:p[0],y:p[1]-17,'text-anchor':'middle',class:`chart-value ${active!=='all'&&active!==key?'region-muted':''}`,fill:r.color});txt.textContent=r.values[i];svg.append(txt)});const name=svgEl('text',{x:pts[0][0]+5,y:pts[0][1]+30,class:`chart-value ${active!=='all'&&active!==key?'region-muted':''}`,fill:r.color});name.textContent=r.name;svg.append(name)});const band=svgEl('rect',{x:m.l+3*(W-m.l-m.r)/4+8,y:m.t,width:(W-m.l-m.r)/4-8,height:H-m.t-m.b,fill:'#111',opacity:'.035'});svg.insertBefore(band,svg.firstChild)}
drawRegion();
$$('.region-btn').forEach(btn=>btn.addEventListener('click',()=>{$$('.region-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');drawRegion(btn.dataset.region)}));

function makeDots(){const box=$('#dotMatrix');for(let i=0;i<243;i++){const d=document.createElement('span');d.className='dot';if(i>=224&&i<236)d.classList.add('minor');else if(i>=236&&i<240)d.classList.add('law');else if(i>=240)d.classList.add('unclassified');box.append(d)}}makeDots();

const choiceText={ignore:'실제 폭발물이나 흉기 사건이라면 국민의 생명과 안전에 돌이킬 수 없는 피해가 발생할 수 있다. 허위 가능성만으로 출동하지 않는 선택은 현실적으로 어렵다.',respond:'허위신고라도 경찰·소방·군 등 대규모 인력이 투입된다. 접수 단계에서 진위를 단정할 수 없기 때문에 경찰은 실제 상황을 전제로 대응할 수밖에 없다.'};
$$('[data-choice]').forEach(btn=>btn.addEventListener('click',()=>{$$('[data-choice]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$('#choiceResult').textContent=choiceText[btn.dataset.choice]}));
